name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Create keystore
      run: |
        keytool -genkey -v -keystore veslogger-release-key.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias veslogger-key -storepass veslogger123 -keypass veslogger123 -dname "CN=VESLogger, OU=Development, O=VESLogger App, L=Istanbul, ST=Istanbul, C=TR"
        
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore veslogger-release-key.keystore -storepass veslogger123 -keypass veslogger123 app/build/outputs/apk/debug/app-debug.apk veslogger-key || echo "Debug APK signing failed"
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore veslogger-release-key.keystore -storepass veslogger123 -keypass veslogger123 app/build/outputs/apk/release/app-release.apk veslogger-key || echo "Release APK signing failed"
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
